default-resources:
 - slurm_account=trc
 - slurm_partition=trc
 - mem_mb="128G"
 - nodes=1
 - tasks=1
cluster:
  mkdir -p logs/`date +"%Y-%m-%d"` &&
  sbatch
    --partition={resources.partition}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/`date +"%Y-%m-%d"`/{rule}-`date +"%Y-%m-%d-%H%M%S"`.out
    --mail-type=ALL