

parameters:
  user: dtadres
  # NOTE: see `bifrost --help` for parameter reference

  build_template:
    # NOTE: parameters with null values are ignored, set to non-null value to override defaults
    reference_image: null
    affine_steps: null
    syn_steps: null
    gradient_step: null
    preprocessing: 'CLAHE'
    # mirror is a boolean ("store_true" action) parameter, any non-null non-boolean values will be parsed as true
    mirror: true

  # NOTE: the --downsample_to parameter is ommitted from all registration steps
  #  due to potential interaction with other steps. You are advised to downsample
  #  images as necessary prior to execution of the pipeline
  register_template_to_fda:
    clahe_kernel_size: null
    moving_clip_limit: -1
    fixed_clip_limit: -1
    # mirror_warp is a boolean parameter, any non-null non-boolean values will be parsed as true
    mirror_warp: true

  register_structural_images_to_template:
    clahe_kernel_size: null
    moving_clip_limit: -1
    fixed_clip_limit: -1
    # mirror_warp is a boolean ("store_true" action) parameter, any non-null non-boolean values will be parsed as true
    mirror_warp: false
    # skip_synthmorph is a boolean ("store_true" action) parameter, any non-null non-boolean values will be parsed as true
    # for this step you probably want to leave set to True
    skip_synthmorph: true

  transform_dependent_images_to_template:
    apply_preprocessing: false

  transform_dependent_images_to_fda:
    apply_preprocessing: false

cluster:
  mkdir -p logs/`date +"%Y-%m-%d"` &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/`date +"%Y-%m-%d"`/{rule}-`date +"%Y-%m-%d-%H%M%S"`.out
    --mail-type=ALL
default-resources:
  - partition="trc"
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 100
keep-going: True
rerun-incomplete: false
printshellcmds: True
scheduler: greedy
use-conda: false
#tmpdir: $SCRATCH # might break things, check -yes breaks things!